/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Cliente;
import fatec.poo.model.ItemPedido;
import fatec.poo.model.Pedido;
import fatec.poo.model.Pessoa;
import fatec.poo.model.Produto;
import fatec.poo.model.Vendedor;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcio Sousa
 */
public class GuiEmitirPedido extends javax.swing.JFrame {
    int numSeq;
    int qtdeTotalItens = 0;
    Double total = 0.0;
    Pedido pedido;
    /**
     * Creates new form GuiEmitirPedido
     */
    public GuiEmitirPedido(ArrayList<Pedido> cadPed, ArrayList<Pessoa> cadPes, ArrayList<Produto> cadPro) {
        initComponents();
        this.setLocationRelativeTo(null);
        pedidos = cadPed;
        pessoas = cadPes;
        produtos = cadPro;
        modTbProduto = (DefaultTableModel)tblItems.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroPedido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFormatDataPedido = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxFormaPagamento = new javax.swing.JComboBox<>();
        btnPesquisarPedido = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtFormatCpfCliente = new javax.swing.JFormattedTextField();
        btnConsultarCliente = new javax.swing.JButton();
        txtDescricaoCliente = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnConsultarVendedor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtFormatCpfVendedor = new javax.swing.JFormattedTextField();
        txtDescricaoVendedor = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigoProduto = new javax.swing.JTextField();
        btnConsultarProduto = new javax.swing.JButton();
        txtDescricaoProduto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnAdicionarItem = new javax.swing.JButton();
        btnRemoverItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtValorTotalPedido = new javax.swing.JTextField();
        txtQtdeItensPedido = new javax.swing.JTextField();
        txtQtdeVendida = new javax.swing.JTextField();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emitir Pedido");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido"));

        jLabel1.setText("Número do Pedido");

        txtNumeroPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroPedidoActionPerformed(evt);
            }
        });

        jLabel2.setText("Data do Pedido");

        try {
            txtFormatDataPedido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFormatDataPedido.setEnabled(false);
        txtFormatDataPedido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFormatDataPedidoFocusLost(evt);
            }
        });

        jLabel3.setText("Forma de Pagamento");

        cbxFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A vista", "A prazo" }));
        cbxFormaPagamento.setSelectedIndex(-1);
        cbxFormaPagamento.setEnabled(false);

        btnPesquisarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Consultar.png"))); // NOI18N
        btnPesquisarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFormatDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxFormaPagamento, 0, 132, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroPedido)
                    .addComponent(btnPesquisarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(txtFormatDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbxFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Cliente"));

        jLabel4.setText("CPF Cliente");

        try {
            txtFormatCpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFormatCpfCliente.setEnabled(false);
        txtFormatCpfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFormatCpfClienteActionPerformed(evt);
            }
        });

        btnConsultarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Consultar.png"))); // NOI18N
        btnConsultarCliente.setEnabled(false);
        btnConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClienteActionPerformed(evt);
            }
        });

        txtDescricaoCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtDescricaoCliente.setEnabled(false);
        txtDescricaoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFormatCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricaoCliente)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(txtFormatCpfCliente)
                    .addComponent(btnConsultarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDescricaoCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Vendedor"));

        btnConsultarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Consultar.png"))); // NOI18N
        btnConsultarVendedor.setEnabled(false);
        btnConsultarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarVendedorActionPerformed(evt);
            }
        });

        jLabel5.setText("CPF Vendedor");

        try {
            txtFormatCpfVendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFormatCpfVendedor.setEnabled(false);

        txtDescricaoVendedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtDescricaoVendedor.setEnabled(false);
        txtDescricaoVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoVendedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFormatCpfVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricaoVendedor)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(txtFormatCpfVendedor)
                    .addComponent(btnConsultarVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDescricaoVendedor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens do Pedido"));

        jLabel6.setText("Código do Produto");

        txtCodigoProduto.setEnabled(false);
        txtCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProdutoActionPerformed(evt);
            }
        });

        btnConsultarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Consultar.png"))); // NOI18N
        btnConsultarProduto.setEnabled(false);
        btnConsultarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarProdutoActionPerformed(evt);
            }
        });

        txtDescricaoProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtDescricaoProduto.setEnabled(false);
        txtDescricaoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoProdutoActionPerformed(evt);
            }
        });

        jLabel7.setText("Qtde Vendida");

        btnAdicionarItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Inserir.png"))); // NOI18N
        btnAdicionarItem.setText("Adicionar Item");
        btnAdicionarItem.setEnabled(false);
        btnAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarItemActionPerformed(evt);
            }
        });

        btnRemoverItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Remover.png"))); // NOI18N
        btnRemoverItem.setText("Remover Item");
        btnRemoverItem.setEnabled(false);
        btnRemoverItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverItemActionPerformed(evt);
            }
        });

        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Prec. Unit.", "Qtde. Vend.", "SubTotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblItems);

        jLabel9.setText("Valor Total do Pedido");

        jLabel10.setText("Quantidade de Itens Pedidos");

        txtValorTotalPedido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtValorTotalPedido.setEnabled(false);
        txtValorTotalPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorTotalPedidoActionPerformed(evt);
            }
        });

        txtQtdeItensPedido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtQtdeItensPedido.setEnabled(false);

        txtQtdeVendida.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnAdicionarItem)
                                .addGap(54, 54, 54)
                                .addComponent(btnRemoverItem)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtDescricaoProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQtdeVendida, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtValorTotalPedido)
                            .addComponent(txtQtdeItensPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(txtCodigoProduto)
                    .addComponent(btnConsultarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtQtdeVendida, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarItem)
                    .addComponent(btnRemoverItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtValorTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtQtdeItensPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Inserir.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.setEnabled(false);
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Remover.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnIncluir)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroPedidoActionPerformed

    private void btnConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClienteActionPerformed
        boolean achou = false;
        //System.out.println(txtFormatCpfCliente.getText());
        
        if(txtFormatDataPedido.isEnabled() == false){
            for(int t = 0; t < pessoas.size(); t++){
                if(pessoas.get(t).getCpf().equals(txtFormatCpfCliente.getText())){
                    if(pessoas.get(t) instanceof Cliente){
                        txtDescricaoCliente.setText(pessoas.get(t).getNome());
                        pedidos.get(posPed).setCliente((Cliente)pessoas.get(t));
                        
                        txtFormatCpfCliente.setEnabled(false);
                        btnConsultarCliente.setEnabled(false);
                        
                        txtFormatCpfVendedor.setEnabled(true);
                        btnConsultarVendedor.setEnabled(true);
                        
                        txtFormatCpfVendedor.requestFocus();
                        
                        achou = true;
                        break;
                    }else{
                        JOptionPane.showMessageDialog(null, "Esse CPF pertence a um Vendedor.", "Cliente não encontrado", HEIGHT);
                        achou = true;
                        break;
                    }
                    
                }
            }
            
            if(achou == false){
                JOptionPane.showMessageDialog(null, "Não foi encontrado o cliente com esse CPF.", "Cliente não encontrado", HEIGHT);
            }
        }
        
    }//GEN-LAST:event_btnConsultarClienteActionPerformed

    private void btnConsultarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarVendedorActionPerformed
        boolean achou = false;
        
        for(int t = 0; t < pessoas.size(); t++){
            if(pessoas.get(t).getCpf().equals(txtFormatCpfVendedor.getText())){
                if(pessoas.get(t) instanceof Vendedor){
                    txtDescricaoVendedor.setText(pessoas.get(t).getNome());
                    pedidos.get(posPed).setVendedor((Vendedor)pessoas.get(t));
                        
                    txtFormatCpfVendedor.setEnabled(false);
                    btnConsultarVendedor.setEnabled(false);
                        
                    txtCodigoProduto.setEnabled(true);
                    btnConsultarProduto.setEnabled(true);
                    
                    txtCodigoProduto.requestFocus();
                        
                    achou = true;
                    break;
                }else{
                    JOptionPane.showMessageDialog(null, "Esse CPF pertence a um Cliente.", "Vendedor não encontrado", HEIGHT);
                    achou = true;
                    break;
                }
                    
            }
        }
            
        if(achou == false){
            JOptionPane.showMessageDialog(null, "Não foi encontrado o Vendedor com esse CPF.", "Vendedor não encontrado", HEIGHT);
        }
        
    }//GEN-LAST:event_btnConsultarVendedorActionPerformed

    private void btnPesquisarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarPedidoActionPerformed
        DecimalFormat vf  = new DecimalFormat("R$ #,##0.00"); 
        boolean novoPedido = true;
        
        try {
            for(int t = 0; t < pedidos.size(); t++){
            if(Integer.parseInt(txtNumeroPedido.getText()) == Integer.parseInt(pedidos.get(t).getNumero())){
                double subtotal;
                double total = 0;
                posPed = t;
                
                txtFormatDataPedido.setText(pedidos.get(t).getDataEmissao());
                
                if(pedidos.get(t).getFormaPagto()){
                    cbxFormaPagamento.setSelectedIndex(0);
                }else{
                    cbxFormaPagamento.setSelectedIndex(1);
                }
                
                txtFormatCpfCliente.setText(pedidos.get(t).getCliente().getCpf());
                txtDescricaoCliente.setText(pedidos.get(t).getCliente().getNome());
                
                txtFormatCpfVendedor.setText(pedidos.get(t).getVendedor().getCpf());
                txtDescricaoVendedor.setText(pedidos.get(t).getVendedor().getNome());
                
                for(int a = 0; a < pedidos.get(t).getItensPedido().size(); a++){
                    String itens[] = {
                        pedidos.get(t).getItensPedido().get(a).getProduto().getCodigo(),
                        pedidos.get(t).getItensPedido().get(a).getProduto().getDescricao(),
                        String.valueOf(vf.format(pedidos.get(t).getItensPedido().get(a).getProduto().getPreco())),
                        String.valueOf(pedidos.get(t).getItensPedido().get(a).getQtdeVendida())
                    };
                    
                    modTbProduto.addRow(itens);
                    subtotal = pedidos.get(t).getItensPedido().get(a).getProduto().getPreco() * pedidos.get(t).getItensPedido().get(a).getQtdeVendida();
                    modTbProduto.setValueAt(vf.format(subtotal), modTbProduto.getRowCount() - 1, 4);
                    total += subtotal;
                }
                
                txtValorTotalPedido.setText(String.valueOf(vf.format(total)));
                txtQtdeItensPedido.setText(String.valueOf(pedidos.get(t).getItensPedido().size()));
                
                txtCodigoProduto.setEnabled(true);
                btnConsultarProduto.setEnabled(true);
                btnRemoverItem.setEnabled(true);
                btnAlterar.setEnabled(true);
                btnExcluir.setEnabled(true);
                
                txtNumeroPedido.setEnabled(false);
                btnPesquisarPedido.setEnabled(false);
                
                novoPedido = false;
                
                break;
            }
        }
        
        if(novoPedido){
            posPed = pedidos.size();
            pedido = new Pedido(txtNumeroPedido.getText(), txtFormatDataPedido.getText());
            txtNumeroPedido.setEnabled(false);
            btnPesquisarPedido.setEnabled(false);
            txtFormatDataPedido.setEnabled(true);
            btnConsultarCliente.setEnabled(true);
            txtFormatDataPedido.requestFocus();
        }
        
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu o erro abaixo.\n" + ex.getMessage(), "Erro de Cadastro", HEIGHT);
        }
        
        
        
        
    }//GEN-LAST:event_btnPesquisarPedidoActionPerformed

    private void txtDescricaoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoClienteActionPerformed

    private void txtDescricaoVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoVendedorActionPerformed

    private void txtCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProdutoActionPerformed

    private void btnConsultarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarProdutoActionPerformed
        boolean achou = false;
        
        for(int t = 0; t < produtos.size(); t++){
            if(produtos.get(t).getCodigo().equals(txtCodigoProduto.getText())){
                txtDescricaoProduto.setText(produtos.get(t).getDescricao());
                txtCodigoProduto.setEnabled(false);
                btnConsultarProduto.setEnabled(false);
                
                btnAdicionarItem.setEnabled(true);
                btnRemoverItem.setEnabled(true);
                txtQtdeVendida.setEnabled(true);
                txtQtdeVendida.requestFocus();
                
                achou = true;
                break;
            }
        }
            
        if(achou == false){
            JOptionPane.showMessageDialog(null, "Não foi encontrado o Código do Produto.", "Produto não encontrado", HEIGHT);
        }
        
    }//GEN-LAST:event_btnConsultarProdutoActionPerformed

    private void txtDescricaoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoProdutoActionPerformed

    private void btnAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarItemActionPerformed
        DecimalFormat vf  = new DecimalFormat("R$ #,##0.00"); 
        Double subtotal;
  
        if(Integer.parseInt(txtQtdeVendida.getText()) == 0){
            JOptionPane.showMessageDialog(null, "A quantidade de produto tem que ser maior do que Zero!", "Quantidade incorreta.", HEIGHT);
        }else{
            
            for(int t = 0; t < produtos.size(); t++){
                if(produtos.get(t).getCodigo().equals(txtCodigoProduto.getText())){
                    if(Double.parseDouble(txtQtdeVendida.getText()) > produtos.get(t).getQtdeEstoque()){
                        JOptionPane.showMessageDialog(null, "Não há a quantidade em Estoque.\nQuantidade em estoque: " + produtos.get(t).getQtdeEstoque(), "Produto não encontrado", HEIGHT);
                        break;
                    }
                    
                    int numeroSeq=1;
                    
                    for(int p = 0; p < pedidos.size(); p++){
                        numeroSeq += pedidos.get(p).getItensPedido().size();
                    }
                    
                    ItemPedido itemPedido = new ItemPedido(numeroSeq, Integer.parseInt(txtQtdeVendida.getText()), produtos.get(t));

                    //Procurando Cliente
                    for(int c = 0; c < pessoas.size(); c++){
                        if(pessoas.get(c).getCpf().equals(txtFormatCpfCliente.getText())){
                            if(pessoas.get(c) instanceof Cliente){
                                pedido.setCliente((Cliente)pessoas.get(c));
                                break;
                            }
                        }
                    }
                    
                    //Procurando Vendedor
                    for(int c = 0; c < pessoas.size(); c++){
                        if(pessoas.get(c).getCpf().equals(txtFormatCpfCliente.getText())){
                            if(pessoas.get(c) instanceof Vendedor){
                                pedido.setVendedor((Vendedor)pessoas.get(c));
                                break;
                            }
                        }
                    }
                    
                    if(pedido.getCliente().getLimiteDisp() > itemPedido.getQtdeVendida() * produtos.get(t).getPreco()){
                        pedidos.add(pedido);
                        itemPedido.setPedido(pedidos.get(posPed));
                        pedidos.get(posPed).addItemPedido(itemPedido);
                        
                        //========= CARREGA GRID ===========               
                        String itens[] = {
                            txtCodigoProduto.getText(),
                            txtDescricaoProduto.getText(),
                            String.valueOf(vf.format(produtos.get(t).getPreco())),
                            String.valueOf(txtQtdeVendida.getText())
                        };
                        
                        qtdeTotalItens += Integer.parseInt(txtQtdeVendida.getText());
                        
                        modTbProduto.addRow(itens);
                        subtotal = itemPedido.getQtdeVendida() * produtos.get(t).getPreco();
                        modTbProduto.setValueAt(vf.format(subtotal), modTbProduto.getRowCount() - 1, 4);
                        total += subtotal;
                        txtQtdeItensPedido.setText(String.valueOf(qtdeTotalItens));
                        txtValorTotalPedido.setText(vf.format(total));
                        //==================================
                        txtCodigoProduto.setText("");
                        txtQtdeVendida.setText("");
                        txtDescricaoProduto.setText("");
                        
                        txtCodigoProduto.setEnabled(true);
                        btnConsultarProduto.setEnabled(true);
                        txtQtdeVendida.setEnabled(false);
                        btnAdicionarItem.setEnabled(false);
                        txtCodigoProduto.requestFocus();
                        
                    }else{
                        JOptionPane.showMessageDialog(null, "Não há saldo suficiente na conta.\nSaldo: " + pedidos.get(t).getCliente().getLimiteDisp(), "Saldo", HEIGHT);
                        break;
                    }
                    
                    break;
                }
            }
        }
    }//GEN-LAST:event_btnAdicionarItemActionPerformed

    private void txtValorTotalPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorTotalPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorTotalPedidoActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtFormatDataPedidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFormatDataPedidoFocusLost
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String dataPedidoString = txtFormatDataPedido.getText();
        
        try {
            sdf.setLenient(false);
            Date dataPedido = sdf.parse(dataPedidoString);
            
            Pedido pedido = new Pedido(txtNumeroPedido.getText(), txtFormatDataPedido.getText());
            pedidos.add(pedido);
            posPed = pedidos.size() - 1;
            txtFormatDataPedido.setEnabled(false);
            txtFormatCpfCliente.setEnabled(true);
            btnConsultarCliente.setEnabled(true);
            txtFormatCpfCliente.requestFocus();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "A data não existe, digite novamente a uma data de pedido válida!\nErro: " + ex.getMessage(), "Data Inválida", HEIGHT);
            txtFormatDataPedido.requestFocus();
        }
        
        
        
    }//GEN-LAST:event_txtFormatDataPedidoFocusLost

    private void txtFormatCpfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFormatCpfClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFormatCpfClienteActionPerformed

    private void btnRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverItemActionPerformed
        if(tblItems.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, 
                    "A linha não foi selecionada",
                    "Aviso",JOptionPane.ERROR_MESSAGE);
        }else{
            int ipRemover = tblItems.getSelectedRow();
            System.out.println(tblItems.getSelectedRow());
            modTbProduto.removeRow(tblItems.getSelectedRow());
            pedido.removeItemPedido(pedidos.get(posPed).getItensPedido().get(ipRemover));
        }
    }//GEN-LAST:event_btnRemoverItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarItem;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultarCliente;
    private javax.swing.JButton btnConsultarProduto;
    private javax.swing.JButton btnConsultarVendedor;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnPesquisarPedido;
    private javax.swing.JButton btnRemoverItem;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbxFormaPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblItems;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JTextField txtDescricaoCliente;
    private javax.swing.JTextField txtDescricaoProduto;
    private javax.swing.JTextField txtDescricaoVendedor;
    private javax.swing.JFormattedTextField txtFormatCpfCliente;
    private javax.swing.JFormattedTextField txtFormatCpfVendedor;
    private javax.swing.JFormattedTextField txtFormatDataPedido;
    private javax.swing.JTextField txtNumeroPedido;
    private javax.swing.JTextField txtQtdeItensPedido;
    private javax.swing.JTextField txtQtdeVendida;
    private javax.swing.JTextField txtValorTotalPedido;
    // End of variables declaration//GEN-END:variables
    
    private ArrayList<Pedido> pedidos;
    private ArrayList<Pessoa> pessoas;
    private ArrayList<Produto> produtos;
    private DefaultTableModel modTbProduto;
    private int posPed;

}
