/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Cliente;
import fatec.poo.model.ItemPedido;
import fatec.poo.model.Pedido;
import fatec.poo.model.Pessoa;
import fatec.poo.model.Produto;
import fatec.poo.model.Vendedor;
import java.util.ArrayList;

/**
 *
 * @author Marcio Sousa
 */
public class GuiMenu extends javax.swing.JFrame {

    /**
     * Creates new form GuiMenu
     */
    public GuiMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        iniciaValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBarVenda = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuItemVendedor = new javax.swing.JMenuItem();
        jMenuItemProduto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuPedido = new javax.swing.JMenu();
        jMenuItemEmitirPedido = new javax.swing.JMenuItem();
        jMenuItemAtualizarLimiteCredito = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Vendas");
        setLocation(new java.awt.Point(0, 0));

        jMenuCadastro.setText("Cadastros");

        jMenuItemCliente.setText("Clientes");
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCliente);

        jMenuItemVendedor.setText("Vendedores");
        jMenuItemVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVendedorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemVendedor);

        jMenuItemProduto.setText("Produtos");
        jMenuItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemProduto);
        jMenuCadastro.add(jSeparator1);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemSair);

        jMenuBarVenda.add(jMenuCadastro);

        jMenuPedido.setText("Pedido");

        jMenuItemEmitirPedido.setText("Emitir Pedido");
        jMenuItemEmitirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEmitirPedidoActionPerformed(evt);
            }
        });
        jMenuPedido.add(jMenuItemEmitirPedido);

        jMenuItemAtualizarLimiteCredito.setText("Atualizar Limite de Crédito");
        jMenuItemAtualizarLimiteCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtualizarLimiteCreditoActionPerformed(evt);
            }
        });
        jMenuPedido.add(jMenuItemAtualizarLimiteCredito);

        jMenuBarVenda.add(jMenuPedido);

        setJMenuBar(jMenuBarVenda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
        new GuiCliente(cadCliVend).setVisible(true);
    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    private void jMenuItemVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVendedorActionPerformed
        new GuiVendedor(cadCliVend).setVisible(true);
    }//GEN-LAST:event_jMenuItemVendedorActionPerformed

    private void jMenuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoActionPerformed
        new GuiProduto(cadProd).setVisible(true);
    }//GEN-LAST:event_jMenuItemProdutoActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemEmitirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEmitirPedidoActionPerformed
        new GuiEmitirPedido(cadPed, cadCliVend, cadProd).setVisible(true);
    }//GEN-LAST:event_jMenuItemEmitirPedidoActionPerformed

    private void jMenuItemAtualizarLimiteCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtualizarLimiteCreditoActionPerformed
        new GuiAtualizaLimiteCredito(cadCliVend).setVisible(true);
    }//GEN-LAST:event_jMenuItemAtualizarLimiteCreditoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBarVenda;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItemAtualizarLimiteCredito;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemEmitirPedido;
    private javax.swing.JMenuItem jMenuItemProduto;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemVendedor;
    private javax.swing.JMenu jMenuPedido;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Pessoa> cadCliVend = new ArrayList<Pessoa>();
    private ArrayList<Produto> cadProd = new ArrayList<Produto>();
    private ArrayList<Pedido> cadPed = new ArrayList<Pedido>();
    
    private void iniciaValores(){
        //CADASTRO DE PRODUTOS
        Produto produto1 = new Produto("1010", "Cerveja");
        produto1.setEstoqueMinimo(10);
        produto1.setPreco(5.60);
        produto1.setQtdeEstoque(10);
        produto1.setUnidadeMedida("unid");
        
        Produto produto2 = new Produto("2020", "Refrigerante");
        produto2.setEstoqueMinimo(20);
        produto2.setPreco(9.00);
        produto2.setQtdeEstoque(20);
        produto2.setUnidadeMedida("unid");
        
        Produto produto3 = new Produto("3030", "Carvão");
        produto3.setEstoqueMinimo(9);
        produto3.setPreco(5.00);
        produto3.setQtdeEstoque(30);
        produto3.setUnidadeMedida("unid");
        
        cadProd.add(produto1);
        cadProd.add(produto2);
        cadProd.add(produto3);
        
        //CADASTRO DE CLIENTE
        Pessoa pessoa1 = new Cliente("111.111.111-11", "Roberta", 300.00);
        pessoa1.setCep("13300-000");
        pessoa1.setCidade("Sorocaba");
        pessoa1.setDdd("11");
        pessoa1.setEndereco("Rua do Jaraguá");
        pessoa1.setTelefone("999999999");
        pessoa1.setUf("RJ");
        ((Cliente)pessoa1).setLimiteCred(800);
        
        //CADASTRO DE VENDEDOR
        Pessoa pessoa2 = new Vendedor("222.222.222-22", "Gabriel", 880.00);
        pessoa2.setCep("13300-005");
        pessoa2.setCidade("Itu");
        pessoa2.setDdd("12");
        pessoa2.setEndereco("Rua do Jucaré");
        pessoa2.setTelefone("222222222");
        pessoa2.setUf("RJ");
        ((Vendedor)pessoa2).setTaxaComissao(2.4);
        
        cadCliVend.add(pessoa1);
        cadCliVend.add(pessoa2);
        
        //CADASTRO ITEMPEDIDO
        ItemPedido itempedido1 = new ItemPedido(1, 2.0, produto1);
        ItemPedido itempedido2 = new ItemPedido(2, 5, produto3);
        
        Pedido pedido1 = new Pedido("123", "10/02/2021");
        pedido1.setCliente((Cliente)pessoa1);
        pedido1.setVendedor((Vendedor)pessoa2);
        pedido1.setDataPagto("02/03/2021");
        pedido1.setFormaPagto(false);
        pedido1.setSituacao(false); 
        cadPed.add(pedido1);
        
        pedido1.addItemPedido(itempedido1);
        pedido1.addItemPedido(itempedido2);
        //itempedido1.setPedido(pedido1);
        
    }
    
}
